# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnu
MACHINETYPE	:= i686
PLATFORM	:= i686-pc-linux-gnu
FULLOSTYPE	:= pc-linux-gnu
SYSTEM_LOADED	:= 1
