#!/bin/sh

# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi Electronic Research Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.

#
# Creates the ASCII form of the TIDIGITS acoustic model suitable
# for use with Sphinx 4. TIDIGITS refers to:
#
# "NIST CD-ROM Version of the Texas Instruments-developed Studio Quality
#  Speaker-Independent Connected-Digit Corpus"
#

ASCII_ZIP=tidigits_8gau_13dCep_16k_40mel_130Hz_6800Hz.ascii.zip

# where the WSJ acoustic model directory is, modify as you need
MODEL_DIR=/lab/speech/sphinx4/data/tidigits_model

PWD=`pwd`

rm -f ${ASCII_ZIP}

cd $MODEL_DIR

zip -r ${ASCII_ZIP} README am.props license.terms unigram.lm unigram.lm.DMP dictionary fillerdict wd_dependent_phone.500.mdef wd_dependent_phone.cd_continuous_8gau/means.ascii wd_dependent_phone.cd_continuous_8gau/mixture_weights.ascii wd_dependent_phone.cd_continuous_8gau/transition_matrices.ascii wd_dependent_phone.cd_continuous_8gau/variances.ascii

mv $ASCII_ZIP $PWD