#!/bin/sh

# Copyright 1999-2002 Carnegie Mellon University.  
# Portions Copyright 2002 Sun Microsystems, Inc.  
# Portions Copyright 2002 Mitsubishi Electronic Research Laboratories.
# All Rights Reserved.  Use is subject to license terms.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.

#
# Creates the ASCII form of the WSJ acoustic model suitable
# for use with Sphinx 4.
#

ASCII_ZIP=wsj_8gau_13dCep_16k_40mel_130Hz_6800Hz.ascii.zip

# where the WSJ acoustic model directory is, modify as you need
MODEL_DIR=/lab/speech/sphinx4/data/wsj

PWD=`pwd`

rm -f ${ASCII_ZIP}

cd $MODEL_DIR

zip -r ${ASCII_ZIP} README am.props license.terms cd_continuous_8gau/*.ascii dict/cmudict.0.6d dict/*.dict dict/fillerdict etc

mv $ASCII_ZIP $PWD