import os
import platform

Help("""
      Type: 'scons shipDictator' to to create and package all dictator related files.

      Type  'scons dictator' to build dictator.jar and its dependencies.

      Type  'scons common' to build common.jar and its dependencies.

      Type  'scons sphinx' to build sphinx.jar and its dependencies.

      Type  'scons audoCollector' to build audioCollector.jar and its dependencies.
             This fails because I don't know where AudioRecorder lives.

      Other sphinx projects are not yet supported.

      Ship output will be placed in the scons_ship directory adjacent to trunk.
      Build output will be placed in the scons_build directory adjacent to trunk.

      This scons script has only been tested on OS X. The dictator builds and runs
      on OS X, but never actually transcribes anything at this point.

      Build outputs will be place in scons_build, which will be created two directories
      below the scons directory

      Ship outputs will be placed in scons_ship, which will also be created two directories
      below the scons directory

      """)

SConscript('sphinx4.py')
Import('sphinx4')
Alias('sphinx4', sphinx4)

SConscript('common.py', exports='sphinx4')
Import('common')
Alias('common', common)

SConscript('dictator.py', exports=['common','sphinx4'])
Import('dictator')
Alias('dictator', dictator)

SConscript('audioCollector.py', exports='common')
Import('audioCollector')
Alias('audioCollector', audioCollector)

SConscript('corpusBrowser.py')
Import('corpusBrowser')
Alias('corpusBrowser', corpusBrowser)

SConscript('shipDictator.py', exports='dictator')
Import('shipDictator')
Alias('shipDictator', shipDictator)